services:
  mongodb:
    image: 'mongo:latest'
    environment:
      - 'MONGO_INITDB_DATABASE=ecommerce'
      - 'MONGO_INITDB_ROOT_PASSWORD=mongodb'
      - 'MONGO_INITDB_ROOT_USERNAME=mongodb'
    ports:
      - '27017'
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=ecommerce'
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5432'